---
title: "Iteration strategies"
author: "Brooks Piper"
date: "2025-10-15"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Iteration strategies

```{r}
library(tidyverse)
# install.packages('infer') # execute once then comment out

# data location
url <- 'https://raw.githubusercontent.com/pstat197/pstat197a/main/materials/labs/lab3-iteration/data/biomarker-clean.csv'

# function for outlier trimming
trim_fn <- function(x){
  x[x > 3] <- 3
  x[x < -3] <- -3
  
  return(x)
}

# read in and preprocess data
asd <- read_csv(url) %>%
  select(-ados) %>%
  # log transform
  mutate(across(.cols = -group, log10)) %>%
  # center and scale
  mutate(across(.cols = -group, ~ scale(.x)[, 1])) %>%
  # trim outliers
  mutate(across(.cols = -group, trim_fn))
```

```{r}
for(i in 1:4){
  print(2*i)
}
```

```{r}
flag_vals <- c(1, 2, 3, 4)
for(i in flag_vals){
  out <- 2*i
  print(out)
}
```

```{r}
rslt <- rep(NA, 4)
for(i in 1:4){
  rslt[i] <- 2*i
}
rslt
```

```{r}
rslt <- rep(NA, 4)
input_vals <- c(15, 27, 3, 12.6)
for(i in 1:4){
  rslt[i] <- 2*input_vals[i]
}
rslt
```

```{r}
rslt <- rep(NA, 4)
input_vals <- rnorm(n = 3)
for(i in 1:4){
  rslt[i] <- 2*input_vals[i]
}

rslt
```

The loop produces an NA because there is no 4th value in input_vals to index/loop through. Therefore, the default value in the 4th index of rslt, NA, remains.

```{r}
x <- asd %>% filter(group == 'ASD') %>% pull(CHIP)
y <- asd %>% filter(group == 'TD') %>% pull(CHIP)
t.test(x, y, var.equal = F)
```

```{r}
t.test(x, y) %>% str()
```

```{r}
t.test(x, y, var.equal = F)$p.value
```

```{r}
n_tests <- 100
p_vals <- rep(NA, n_tests)
for(i in 1:n_tests){
  x <- asd %>% filter(group == 'ASD') %>% pull(i + 1)
  y <- asd %>% filter(group == 'TD') %>% pull(i + 1)
  p_vals[i] <- t.test(x, y, var.equal = F)$p.value
}
```

```{r}
tibble(protein = colnames(asd)[2:(n_tests + 1)],
       p = p_vals)
```

```{r}
n_tests <- 100
rslt <- tibble(protein = colnames(asd)[2:(n_tests + 1)],
               p = NA)
for(i in 1:n_tests){
  x <- asd %>% filter(group == 'ASD') %>% pull(i + 1)
  y <- asd %>% filter(group == 'TD') %>% pull(i + 1)
  rslt$p[i] <- t.test(x, y, var.equal = F)$p.value
}
```

```{r}
# Follow the example above to write a loop that stores both the 
# p-values and the estimated differences for the first 50 proteins.

n_tests <- 50 # first 50 proteins
rslt <- tibble(protein = colnames(asd)[2:(n_tests + 1)],
               p = NA, estimated_difference = NA)
for(i in 1:n_tests){
  x <- asd %>% filter(group == 'ASD') %>% pull(i + 1)
  y <- asd %>% filter(group == 'TD') %>% pull(i + 1)
  t_test <- t.test(x, y, var.equal = F)
  rslt$p[i] <- t_test$p.value
  rslt$estimated_difference[i] <- t_test$estimate[1] - t_test$estimate[2]
}

rslt
```

```{r}
vals <- rnorm(n = 4)
simple_fn <- function(x){2*x}
lapply(vals, simple_fn)
```

```{r}
sapply(vals, simple_fn)
```

```{r}
# apply a function to an index set
simple_fn_ix <- function(i){2*vals[i]}
rslt_apply <- sapply(1:length(vals), simple_fn_ix)

# equivalent for loop
rslt_loop <- rep(NA, length(vals))
for(i in 1:length(vals)){
  rslt_loop[i] <- 2*vals[i]
}

# compare
rbind(rslt_loop, rslt_apply)
```

```{r}
# number of tests to perform
n_tests <- 100

# convert to a list
asd_list <- asd %>% 
  select(1:(n_tests + 1)) %>%
  pivot_longer(cols = -group,
               names_to = 'protein',
               values_to = 'level') %>%
  group_by(protein) %>%
  group_split()

# first entry in list
asd_list[[1]]
```

```{r}
t.test(level ~ group, data = asd_list[[1]])
```

```{r}
# p value for ith protein
tt_fn <- function(i){
  t.test(level ~ group, data = asd_list[[i]])$p.value
}

# check
tt_fn(1)
```

```{r}
sapply(1:n_tests, tt_fn)
```

```{r}
start <- Sys.time()
rslt <- sapply(1:n_tests, tt_fn)
end <- Sys.time()

end - start
```

```{r}
start <- Sys.time()
n_tests <- 100
rslt <- tibble(protein = colnames(asd)[2:(n_tests + 1)],
               p = NA)
for(i in 1:n_tests){
  x <- asd %>% filter(group == 'ASD') %>% pull(i + 1)
  y <- asd %>% filter(group == 'TD') %>% pull(i + 1)
  rslt$p[i] <- t.test(x, y, var.equal = F)$p.value
}
end <- Sys.time()

end - start
```

```{r}
tt_fn <- function(i){
  test_rslt <- t.test(level ~ group, data = asd_list[[i]])
  out <- c(pval = test_rslt$p.value, 
           tstat = test_rslt$statistic)
  out
}

tt_fn(1)
```

```{r}
sapply(1:5, tt_fn) %>% t() %>% as_tibble()
```

```{r}
# 1. Use sapply to obtain the estimated differences and standard errors for the 
# groupwise comparisons for the first 50 proteins.

tt_fn <- function(i){
  t_test = t.test(level ~ group, data = asd_list[[i]])
  c(
    estimated_difference = t_test$estimate[1] - t_test$estimate[2],
    std_error = t_test$stderr
  )
}

n_tests = 50 # first 50 proteins
rslt <- sapply(1:n_tests, tt_fn)

# 2. Arrange the result in a data frame with a column indicating the protein, a
# column indicating the estimated group difference, and a column indicating the standard error.

rslt %>% t() %>% as_tibble()
```

```{r}
asd_nested <- asd %>%
  pivot_longer(-group, 
               names_to = 'protein', 
               values_to = 'level') %>%
  nest(data = c(level, group))

asd_nested %>% head(5)
```

```{r}
asd_nested %>%
  slice(1L) %>%
  pull(data)
```

```{r}
tt_fn <- function(.df){
  t.test(level ~ group, data = .df)
}

rslt <- asd_nested %>%
  slice(1:10) %>%
  mutate(ttest.out = map(data, tt_fn))

rslt
```

```{r}
rslt %>% slice(1L) %>% pull(ttest.out)
```

```{r}
asd_nested %>% 
  slice(1L) %>% 
  unnest(cols = data) %>% 
  infer::t_test(formula = level ~ group,
         order = c('ASD', 'TD'),
         alternative = 'two-sided',
         var.equal = F)
```

```{r}
# wrapper around infer::t_test
tt_fn <- function(.df){
  infer::t_test(.df, 
         formula = level ~ group,
         order = c('ASD', 'TD'),
         alternative = 'two-sided',
         var.equal = F)
}

# compute test results
tt_out <- asd_nested %>%
  slice(1:n_tests) %>%
  mutate(ttest = map(data, tt_fn))

# preview
tt_out %>% head(4)
```

```{r}
tt_out %>% 
  unnest(ttest) %>%
  head(4)
```

```{r}
# time it
start <- Sys.time()
tt_out <- asd_nested %>%
  slice(1:n_tests) %>%
  mutate(ttest = map(data, tt_fn))
end <- Sys.time()

end - start
```

```{r}
# bonferroni correction
tt_out %>% 
  unnest(ttest) %>%
  mutate(p_adj = p_value*n_tests) %>%
  select(protein, p_value, p_adj) %>%
  arrange(p_adj) %>%
  head(4)
```

```{r}
# Implement the Benjamini-Hochberg correction

tt_out <- asd_nested %>%
  mutate(ttest = map(data, tt_fn))

tt_out %>% 
  unnest(ttest) %>%
  # 1. Sort the raw  p-values using arrange()
  arrange(p_value) %>%
  # 2. Add a rank column of consecutive integers (neat trick: try using row_number())
  mutate(rank = row_number(p_value)) %>%
  # 3. Add a column p_adj containing m/i*p_i where m is the number of tests, 
  # i is the rank of the p-value, and p_i is the ith smallest p-value
  mutate(p_adj = nrow(tt_out)/rank * p_value) %>%
  # Find the collection of proteins with significantly different serum levels 
  # between the ASD and TD groups while controlling the false discovery rate at 1%.
  filter(p_adj <= 0.01) %>%
  select(protein, p_value, p_adj)
  
```

