---
title: "Lab 3"
author: "Adarsh Nagar"
date: "2025-10-15"
output: html_document
---
#1
```{r setup, include=FALSE}

library(tidyverse)
# install.packages('infer') # execute once then comment out

# data location
url <- 'https://raw.githubusercontent.com/pstat197/pstat197a/main/materials/labs/lab3-iteration/data/biomarker-clean.csv'

# function for outlier trimming
trim_fn <- function(x){
  x[x > 3] <- 3
  x[x < -3] <- -3
  
  return(x)
}

# read in and preprocess data
asd <- read_csv(url) %>%
  select(-ados) %>%
  # log transform
  mutate(across(.cols = -group, log10)) %>%
  # center and scale
  mutate(across(.cols = -group, ~ scale(.x)[, 1])) %>%
  # trim outliers
  mutate(across(.cols = -group, trim_fn))

```


#2
```{r}
n_tests <- 50
rslt <- tibble(protein = colnames(asd)[2:(n_tests + 1)],
               p = NA)

for(i in 1:n_tests){
  x <- asd %>% filter(group == 'ASD') %>% pull(i + 1)
  y <- asd %>% filter(group == 'TD') %>% pull(i + 1)
  rslt$p[i] <- t.test(x, y, var.equal = F)$p.value
  rslt$diff[i] <- abs(t.test(x, y, var.equal = F)$estimate[2] - t.test(x, y, var.equal = F)$estimate[1])
}
print(rslt)
```


#3
```{r}

# convert to a list
asd_list <- asd %>% 
  select(1:(n_tests + 1)) %>%
  pivot_longer(cols = -group,
               names_to = 'protein',
               values_to = 'level') %>%
  group_by(protein) %>%
  group_split()

# first entry in list
asd_list[[1]]

# 1)
tt_fn <- function(i){
  test_rslt <- t.test(level ~ group, data = asd_list[[i]])
  out <- c(protein = colnames(asd)[i+1],estimated_difference = as.numeric(abs(test_rslt$estimate[1] - test_rslt$estimate[2])), stderror = test_rslt$stderr)
  out
}


# 2) 
df <- sapply(1:50, tt_fn) %>% t() %>% as_tibble() |> data.frame()
```



#3
```{r}
library(tidyverse)
asd_nested <- asd %>%
  pivot_longer(-group, 
               names_to = 'protein', 
               values_to = 'level') %>%
  nest(data = c(level, group))

asd_nested %>% head(5)

asd_nested %>%
  slice(1L) %>%
  pull(data)


tt_fn <- function(.df){
  t.test(level ~ group, data = .df)
}

rslt <- asd_nested %>%
  slice(1:10) %>%
  mutate(ttest.out = map(data, tt_fn))

asd_nested %>% 
  slice(1L) %>% 
  unnest(cols = data) %>% 
  infer::t_test(formula = level ~ group,
         order = c('ASD', 'TD'),
         alternative = 'two-sided',
         var.equal = F)

# wrapper around infer::t_test
library(infer)
tt_fn <- function(.df){
  infer::t_test(.df, 
         formula = level ~ group,
         order = c('ASD', 'TD'),
         alternative = 'two-sided',
         var.equal = F)
}

# compute test results
tt_out <- asd_nested %>%
  slice(1:n_tests) %>%
  mutate(ttest = map(data, tt_fn))


#3 (Applied to all 1317 tests)
tt_out %>% 
  unnest(ttest) %>%
  arrange(p_value) |>
  mutate(rank = row_number(p_value))|>
  mutate(p_adj = (nrow(tt_out)/rank) * p_value) |>
  filter(p_adj < 0.01)

```

